name = "SketchyCGAL"
uuid = "b13a172e-2abe-4c98-9673-1ccf91d4745f"
authors = ["Ngoc Hoang Anh Mai <maihoanganh6@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
