name = "SketchyCGAL"
uuid = "b47e9d54-75b6-440c-8f26-ba88c971f681"
authors = ["Ngoc Hoang Anh Mai <maihoanganh6@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
