name = "SketchyCGAL"
uuid = "8d9e00f7-cecc-4793-8b3e-56b6af0f38ce"
authors = ["Ngoc Hoang Anh Mai <maihoanganh6@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
