name = "SketchyCGAL"
uuid = "8d9e00f7-cecc-4793-8b3e-56b6af0f38ce"
authors = ["Ngoc Hoang Anh Mai <maihoanganh6@gmail.com>"]
version = "0.1.0"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"
